VEX_DIR=/home/p/ropc-repo/bap-0.4/VEX
LIBASMIR_CXXFLAGS=-I/home/p/ropc-repo/bap-0.4/VEX/pub -I/home/p/ropc-repo/bap-0.4/src/include -g -O2
LIBASMIR_LDFLAGS=-L/home/p/ropc-repo/bap-0.4/VEX -L/home/p/ropc-repo/bap-0.4/src 
LIBASMIR_LIBS=-lasmir -lvex -lbfd -ldl -liberty
